name: Build & Deploy
on: [push]

env:
  JEKYLL_SITE_DIR: _site/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build site
        uses: helaili/jekyll-action@v2
        with:
          build_only: true
          jekyll_build_options: --destination ${{ env.JEKYLL_SITE_DIR }}
      - name: Archive site
        uses: actions/upload-artifact@master
        with:
          name: site
          path: ${{ env.JEKYLL_SITE_DIR }}
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download site
        uses: actions/download-artifact@master
        with:
          name: site
          path: ${{ env.JEKYLL_SITE_DIR }}
      - name: Deploy docs
        # awscli comes pre-installed per docs
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software
        run: aws s3 sync ${{ env.JEKYLL_SITE_DIR }} s3://blog.vogt4nick.com --region=us-east-1 --delete --acl public-read --no-progress
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
