name: Build & Deploy
on: [push]

env:
  HUGO_SITE_DIR: _site/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
      - name: Update theme
        # Required if theme is added as submodule
        run: git submodule update --init --recursive
      - name: Build site
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ${{ env.HUGO_SITE_DIR }}
      - name: Archive site
        uses: actions/upload-artifact@master
        with:
          name: site
          path: ${{ env.HUGO_SITE_DIR }}
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download site
        uses: actions/download-artifact@master
        with:
          name: site
          path: ${{ env.HUGO_SITE_DIR }}
      - name: Deploy site
        # awscli comes pre-installed per docs
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software
        run: aws s3 sync ${{ env.HUGO_SITE_DIR }} s3://blog.vogt4nick.com --region=us-east-1 --delete --acl public-read --no-progress
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
